name: ci

on: [push]

env:
  VERSION: 1

jobs:
  ci-flow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache node_modules
        if: github.ref == 'refs/heads/master'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-app-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-app-dependencies-
      - name: install dependencies
        if: github.ref == 'refs/heads/master'
        run: npm ci
      - name: run linting
        run: npm run lint
        if: github.ref == 'refs/heads/master'
      - name: run prettier
        run: npm run prettier:check
        if: github.ref == 'refs/heads/master'
      - name: run unittest
        run: npm run test
        if: github.ref == 'refs/heads/master'
      - name: expose bucket tags (get from aws)
        id: exposeBucketTags
        run: |
          bucketTagsContent=$(cat ./bucket.json)
          echo "::set-output name=bucketTags::$bucketTagsContent"
      - name: get version
        id: currentVersion
        uses: ./.github/actions/version
        with:
          bucketTagsJson: ${{ steps.exposeBucketTags.outputs.bucketTags }}
      - name: print version
        run: echo "${{ steps.exposeBucketTags.outputs.version }}"
      - name: build production artifacts
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Start prod building application version $VERSION"
          VERSION=$VERSION npm run build
      - name: build dev artifacts
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Start dev building application version $VERSION"
          VERSION=$VERSION npm run build:dev
