name: ci

on: [push]

env:
  VERSION: 1

jobs:
  ci-flow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache node_modules
        if: github.ref == 'refs/heads/master'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-app-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-app-dependencies-
      - name: install dependencies
        if: github.ref == 'refs/heads/master'
        run: npm ci
      - name: run linting
        run: npm run lint
        if: github.ref == 'refs/heads/master'
      - name: run prettier
        run: npm run prettier:check
        if: github.ref == 'refs/heads/master'
      - name: run unittest
        run: npm run test
        if: github.ref == 'refs/heads/master'
      - name: expose bucket tags (get from aws)
        id: expose-bucket-tags
        run: |
          bucketTagsContent=$(cat ./bucket.json)
          bucketTagsContent="${bucketTagsContent//'%'/'%25'}"
          bucketTagsContent="${bucketTagsContent//$'\n'/'%0A'}"
          bucketTagsContent="${bucketTagsContent//$'\r'/'%0D'}"
          echo "::set-output name=bucketTags::$bucketTagsContent"
      - name: execute custom action
        uses: ./.github/actions/version
        id: custom-action
        env:
          param: ${{steps.expose-bucket-tags.outputs.bucketTags}}
        with:
          param1: ${{env.param}}
      - name: expose version variable
        env:
          version: ${{ steps.custom-action.outputs.version }}
        run: |
          echo "current version => $version"
          echo "::set-output name=currentVersion::$version"
      - name: build production artifacts
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Start prod building application version $VERSION"
          VERSION=$VERSION npm run build
      - name: build dev artifacts
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Start dev building application version $VERSION"
          VERSION=$VERSION npm run build:dev
