name: Deploy

on:
  push:
    branches:
        - "master"


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: "master"
      - name: print deployment
        run: echo deployment
