name: Dispatch workflow

on:
  repository_dispatch:
    types: [deploy]

jobs:
  run-dispatch-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: npm install
        run: npm i
      - name: build
        run: npm run build
      - name: list files
        run: ls -a
      - name: print payload
        run: |
          echo ${{ github.event.client_payload }}
          echo running on branch ${GITHUB_REF##*/}


# curl -X POST \
#   https://api.github.com/repos/chenlevin89/Angular-course/dispatches \
#   -H 'Accept: application/vnd.github.v3+json' \
#   -H 'Content-Type: application/json' \
#   -H 'Authorization: Bearer 4207fc4139d69d07912aa4af2c190a9ad731f60d' \
#   -H 'cache-control: no-cache' \
#   -d '{
#         "event_type": "deploy",
#         "client_payload": {
#                 "dev": "production",
#                 "server": "develop"
#         }
# }'
