name: Dispatch workflow

on:
  repository_dispatch:
    types: [deploy]

jobs:
  run-dispatch-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: build
        run: npm run build
      - name: list files
        run: ls -a
      - name: print payload
        run: |
          echo {{ github.event.client_payload }}
          echo running on branch ${GITHUB_REF##*/}
