name: Test Custom action

on: [push]


env:
  LOCAL_ENV: 'Workflow local env'
  CUSTOM_TEST_SECRETS: ${{ secrets.CUSTOM_TEST_SECRETS }}

jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute custom action
        uses: ./.github/actions/custom
        id: custom-action
        with:
          param1: 'Hello world'
      - name: Print custom action result
        run: echo "Custom action result ${{ steps.custom-action.outputs.result }} "
