name: Shell commands

on:
  push:
    branches-ignore:
        - "master"

env:
  LOCAL_ENV: 'Workflow local env'

jobs:
  git-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: prints
        run: |
          pwd
          echo ${LOCAL_ENV}
