name: Shell commands

on:
  push:
    branches-ignore:
        - "master"

env:
  LOCAL_ENV: 'Workflow local env'
  CUSTOM_TEST_SECRETS: ${{ secrets.CUSTOM_TEST_SECRETS }}

jobs:
  git-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: prints
        run: |
          pwd
          echo ${LOCAL_ENV}
          echo ${CUSTOM_TEST_SECRETS}
